package core.webContent.mapper;

import core.webContent.model.DataSourceDO;

public interface DataSourceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource_message
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource_message
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    int insert(DataSourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource_message
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    int insertSelective(DataSourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource_message
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    DataSourceDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource_message
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    int updateByPrimaryKeySelective(DataSourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource_message
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    int updateByPrimaryKey(DataSourceDO record);
}