package core.webContent.mapper;

import core.webContent.model.FetchedContentDO;

public interface FetchedContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fetched_content
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fetched_content
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    int insert(FetchedContentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fetched_content
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    int insertSelective(FetchedContentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fetched_content
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    FetchedContentDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fetched_content
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    int updateByPrimaryKeySelective(FetchedContentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fetched_content
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(FetchedContentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fetched_content
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    int updateByPrimaryKey(FetchedContentDO record);
}