package core.webContent.model;

import java.io.Serializable;
import java.util.Date;

public class DataSourceDO implements Serializable {
   
	private static final long serialVersionUID = 9020500949511484817L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datasource_message.id
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datasource_message.ds_title
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    private String dsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datasource_message.ds_url
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    private String dsUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datasource_message.insert_Time
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datasource_message.update_Time
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    private Date updateTime;
    private String isFetched;
    private Date fecthedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datasource_message.id
     *
     * @return the value of datasource_message.id
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datasource_message.id
     *
     * @param id the value for datasource_message.id
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datasource_message.ds_title
     *
     * @return the value of datasource_message.ds_title
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    public String getDsTitle() {
        return dsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datasource_message.ds_title
     *
     * @param dsTitle the value for datasource_message.ds_title
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    public void setDsTitle(String dsTitle) {
        this.dsTitle = dsTitle == null ? null : dsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datasource_message.ds_url
     *
     * @return the value of datasource_message.ds_url
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    public String getDsUrl() {
        return dsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datasource_message.ds_url
     *
     * @param dsUrl the value for datasource_message.ds_url
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    public void setDsUrl(String dsUrl) {
        this.dsUrl = dsUrl == null ? null : dsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datasource_message.insert_Time
     *
     * @return the value of datasource_message.insert_Time
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datasource_message.insert_Time
     *
     * @param insertTime the value for datasource_message.insert_Time
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datasource_message.update_Time
     *
     * @return the value of datasource_message.update_Time
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datasource_message.update_Time
     *
     * @param updateTime the value for datasource_message.update_Time
     *
     * @mbggenerated Tue Nov 12 13:57:26 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public String getIsFetched() {
		return isFetched;
	}

	public void setIsFetched(String isFetched) {
		this.isFetched = isFetched;
	}

	public Date getFecthedTime() {
		return fecthedTime;
	}

	public void setFecthedTime(Date fecthedTime) {
		this.fecthedTime = fecthedTime;
	}
}