package core.webContent.model;

import java.io.Serializable;
import java.util.Date;

public class FetchedContentDO implements Serializable {
    
	private static final long serialVersionUID = -98761471959451183L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetched_content.id
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetched_content.web_Url
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    private String webUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetched_content.web_Title
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    private String webTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetched_content.fecthed_Time
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    private Date fecthedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetched_content.update_Time
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetched_content.web_Content
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    private String webContent;

    private Long dsId;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetched_content.id
     *
     * @return the value of fetched_content.id
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetched_content.id
     *
     * @param id the value for fetched_content.id
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetched_content.web_Url
     *
     * @return the value of fetched_content.web_Url
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    public String getWebUrl() {
        return webUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetched_content.web_Url
     *
     * @param webUrl the value for fetched_content.web_Url
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    public void setWebUrl(String webUrl) {
        this.webUrl = webUrl == null ? null : webUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetched_content.web_Title
     *
     * @return the value of fetched_content.web_Title
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    public String getWebTitle() {
        return webTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetched_content.web_Title
     *
     * @param webTitle the value for fetched_content.web_Title
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    public void setWebTitle(String webTitle) {
        this.webTitle = webTitle == null ? null : webTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetched_content.fecthed_Time
     *
     * @return the value of fetched_content.fecthed_Time
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    public Date getFecthedTime() {
        return fecthedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetched_content.fecthed_Time
     *
     * @param fecthedTime the value for fetched_content.fecthed_Time
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    public void setFecthedTime(Date fecthedTime) {
        this.fecthedTime = fecthedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetched_content.update_Time
     *
     * @return the value of fetched_content.update_Time
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetched_content.update_Time
     *
     * @param updateTime the value for fetched_content.update_Time
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetched_content.web_Content
     *
     * @return the value of fetched_content.web_Content
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    public String getWebContent() {
        return webContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetched_content.web_Content
     *
     * @param webContent the value for fetched_content.web_Content
     *
     * @mbggenerated Mon Nov 11 17:07:06 CST 2013
     */
    public void setWebContent(String webContent) {
        this.webContent = webContent == null ? null : webContent.trim();
    }

	public Long getDsId() {
		return dsId;
	}

	public void setDsId(Long dsId) {
		this.dsId = dsId;
	}
}